### ISSUE TITLE
cider-hydra is not in Melpa

### ISSUE THREAD

**Issue by leathekd** [clojure-emacs/cider-hydra#1]
I'm not sure if it is intentional (maybe this package is still a work in progress) but I noticed that the package is missing from Melpa so the instructions in the readme will not work.

**Comment by bbatsov** [comment]
Just an oversight on our part. Someone should submit a recipe there.

**Comment by leathekd** [comment]
Ok, just making sure.  I'll go ahead and submit a recipe.

**Comment by bbatsov** [comment]
Great!

**Comment by leathekd** [comment]
I'll close this out and monitor the PR over on the Melpa repo.  I don't anticipate any issues but will reach out if I run into any.  Thanks.
