### ISSUE TITLE
cider-interaction.el was renamed to cider-eval.el

### ISSUE THREAD

**Issue by tarsius** [clojure-emacs/cider-hydra#5]
See https://github.com/clojure-emacs/cider/commit/ac9cb611f422f1133a9520efa469687c0cd3af18
and https://github.com/clojure-emacs/cider/issues/2203.

**Comment by tarsius** [comment]
Friendly ping!

**Comment by bbatsov** [comment]
Guess I owe you one today - fixed. :-)

**Comment by tarsius** [comment]
;-)
